name: docker-image-build

on:
  push:
    branches:
      - master
      - testWorkflow

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: maven:3.8.2-jdk-17

    steps:
    - name: Checks code
      uses: actions/checkout@v3

    - name: Login
      run: docker login -u ${{ secrets.USERNAME_DOCKERHUB }} -p ${{ secrets.PASSWORD_DOCKERHUB }}

    - name: Pull Image
      run: docker pull ${secrets.USERNAME_DOCKERHUB}/wildfly-image-maven:latest

    - name: Date & Time
      id: date
      run: echo "::set-output name=time::$(date +'%Y%m%d%H%M%S')"

    - name: Build and Push new image
      run: |
        TIME=${{ steps.date.outputs.time }}
        docker build -t ${secrets.USERNAME_DOCKERHUB}/wildfly-image-maven:${TIME} .
        docker push ${secrets.USERNAME_DOCKERHUB}/wildfly-image-maven:${TIME}
