name: docker-image-build

on:
  push:
    branches:
      - master
      - testWorkflow

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checks code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
       distribution: 'temurin'
       java-version: "21" 

    - name: Build
      run: mvn clean install
      working-directory: .  

    - name: Test
      run: mvn test
      working-directory: .

    - name: Login
      run: docker login -u ${{ secrets.USERNAME_DOCKERHUB }} -p ${{ secrets.PASSWORD_DOCKERHUB }}

    - name: Pull Image
      # Pull custom image from Dockerhub
      run: docker pull ${{ secrets.USERNAME_DOCKERHUB }}/wildfly-image

    - name: Build and Push new image
      # Git log/hash for new image to easily know what code image specifies
      run: |
        GIT_LOG=$(git log --format="%h" -n 1) 
        docker build -t ${{ secrets.USERNAME_DOCKERHUB }}/wildfly-image:${GIT_LOG} .
        docker push ${{ secrets.USERNAME_DOCKERHUB }}/wildfly-image:${GIT_LOG}

